DROP TABLE IF EXISTS COORDENADAS;

CREATE TABLE
    IF NOT EXISTS COORDENADAS (

        CAPACIDAD_BELICA INTEGER,
        GEOPOSICIONAMIENTO varchar(4),
        ARSENAL varchar(10)

    );

------------------------------------------------------------------------
-- CEDULA:1728848274
--INVERSA:4728488271
INSERT INTO COORDENADAS ( CAPACIDAD_BELICA, GEOPOSICIONAMIENTO, ARSENAL) VALUES (4, 'GPS4', 'acd');
INSERT INTO COORDENADAS ( CAPACIDAD_BELICA, GEOPOSICIONAMIENTO, ARSENAL) VALUES (7, 'GPS7', 'aaabbct');
INSERT INTO COORDENADAS ( CAPACIDAD_BELICA, GEOPOSICIONAMIENTO, ARSENAL) VALUES (2, 'GPS2', 'ac');
INSERT INTO COORDENADAS ( CAPACIDAD_BELICA, GEOPOSICIONAMIENTO, ARSENAL) VALUES (8, 'GPS8', 'abbccdt');
INSERT INTO COORDENADAS ( CAPACIDAD_BELICA, GEOPOSICIONAMIENTO, ARSENAL) VALUES (4, 'GPS4', 'acd');
INSERT INTO COORDENADAS ( CAPACIDAD_BELICA, GEOPOSICIONAMIENTO, ARSENAL) VALUES (8, 'GPS8', 'abbccdt');
INSERT INTO COORDENADAS ( CAPACIDAD_BELICA, GEOPOSICIONAMIENTO, ARSENAL) VALUES (8, 'GPS8', 'abbccdt');
INSERT INTO COORDENADAS ( CAPACIDAD_BELICA, GEOPOSICIONAMIENTO, ARSENAL) VALUES (2, 'GPS2', 'ac');
INSERT INTO COORDENADAS ( CAPACIDAD_BELICA, GEOPOSICIONAMIENTO, ARSENAL) VALUES (7, 'GPS7', 'aaabbct');
INSERT INTO COORDENADAS ( CAPACIDAD_BELICA, GEOPOSICIONAMIENTO, ARSENAL) VALUES (1, 'GPS1', 'ab');
SELECT * FROM COORDENADAS;


------------------------------------------------------------------------
------------------------------------------------------------------------
------------------------------------------------------------------------


