DROP TABLE IF EXISTS USUARIOS;

CREATE TABLE
    IF NOT EXISTS BOMB (

        ID_BOMBA INTEGER PRIMARY KEY AUTOINCREMENT,
        NOMBRE_BOMBA varchar(20),
        PATRON varchar(20)

    );
    INSERT INTO BOMB (NOMBRE_BOMBA, PATRON) VALUES ('BOMB-II','^a*b+c$');
    INSERT INTO BOMB (NOMBRE_BOMBA, PATRON) VALUES ('BOMB-IP','^ab*c+dt$');
    INSERT INTO BOMB (NOMBRE_BOMBA, PATRON) VALUES ('BOMB-IPI','^a+bc*$');

    SELECT * FROM BOMB;
